### PR TITLE
Simplify many release notes entries

### PR DESCRIPTION
**Pull request by pcahyna**
Do not include every commit message from "git log", shorten to show just a summary of the changes that are visible to the user.

Remove some changelog entries about purely internal changes and entries for changes that got subsequently reverted.

### CODE REVIEW

**Comment by pcahyna** [comment]
@jsmeix I dared to touch some entries by you, therefore requesting your review.

I would also like to propose to remove entries of the type `Use 'source' instead of '.'`, as those are not user-visible changes.
Same for "Make XYZ ASCII".

**Review by jsmeix — APPROVED** [review]
Less is more!

**Comment by jsmeix** [comment]
@pcahyna 
feel free to remove or shorten what is not meaningful
for the user, cf. the header text of the
"Details (mostly in chronological order - newest topmost)"
section that reads (excerpt)
```
Only changes of the ReaR software and its documentation
that could be of common interest are listed here.
```

**Comment by pcahyna** [comment]
@jsmeix done

**Comment by pcahyna** [comment]
Going to merge

**Review by jsmeix — APPROVED** [review]

**Comment by jsmeix** [comment]
@pcahyna 
thank you!

I will do the doc/rear-release-notes.txt
related things tomorrow, cf.
https://github.com/rear/rear/pull/3370

**Pull request merged**
