### PR TITLE
Fix link to SEP Sesam homepage

### PR DESCRIPTION
**Pull request by abbbi**
hi,

unfortunately our website URL's have changed. Fix link to SEP Page.

Thanks.

### CODE REVIEW

**Comment by jsmeix** [comment]
@abbbi 
FYI
in the ReaR scripts I found
that
usr/share/rear/restore/SESAM/default/400_restore_backup.sh
contains
`http://wiki.sepsoftware.com/wiki/index.php/Disaster_Recovery_for_Linux_3.0_en`
and
usr/share/rear/conf/default.conf
contains
`# BACKUP=SESAM  (SEP Sesam: http://www.sep.de)`

**Comment by abbbi** [comment]
hi,

these are still valid :)

**Comment by abbbi** [comment]
Anything that speaks against merge? Thanks :)

**Comment by gdha** [comment]
@abbbi done the merge -thanks for the update

**Pull request merged**
